// export const DID_GET_CARDS = 'DID_GET_CARDS'
// export const DID_GET_CARD = 'DID_GET_CARD'
// export const DID_CREATE_CARD = 'DID_CREATE_CARD'
// export const DID_DELETE_CARD = 'DID_DELETE_CARD'

export const SET_VIEWER = 'set_viewer'
export const SET_COURSES = 'set_courses'
export const SET_COURSE = 'ser_course'
export const ADD_COURSE = 'add_course'
export const FETCH_COURSES = 'fetch_courses'
export const AUTH_USER = 'auth_user'
export const UNAUTH_USER = 'unauth_user'
export const AUTH_ERROR = 'auth_error'
export const FETCH_MESSAGE = 'fetch_message'
